### ISSUE TITLE
Error with (I think) Ancient warfare

### ISSUE THREAD

**Issue by EvertX** [XzeroAir/Trinkets-1.12.2#10]
Forge 2773
Trinkets 0.20
I'm getting errors (using vanillafixes so it prevents a crash) whenever I am near certain ancient warfare structures. See log here: https://paste.dimdev.org/yoyeveyupa.mccrash

**Comment by XzeroAir** [comment]
Hmm, I'll look into it as soon as I can

**Comment by XzeroAir** [comment]
I Was Able to Reproduce that Crash report using Ancient Warfare, VanillaFixes, and my Mod, I'll add some Cast/Entity Checks in my dev environment and see if that stops the crash report, I Also tried Removing VanillaFixes and going around the same areas, and newly generated Areas, I Can't produce an Actual Crash, So I think it might just be something VanillaFixes is doing that kicks up the report

**Comment by XzeroAir** [comment]
Yeah, Adding a Check removed the Error, I'll upload a hotfix, Closing this now
