### ISSUE TITLE
configs aren't working

### ISSUE THREAD

**Issue by Gelox1209** [XzeroAir/Trinkets-1.12.2#12]
setting the configs to disable flowing still causes the player to fly, I set the config to false and restarted the server like so: `    "server settings" {
        # Fairy's Ring Climbing Ability. Set to False to Disable. Default True
        B:Climbing=true

        # Creative Flight when wearing the Fairies Ring. Set to False to Disable. Default True
        B:"Creative Flight"=false

        # Dwarves Ring Special Fortune Like Effect. Set to False to Disable. Default True
        B:"Dwarves Ring Fortune Effect"=true

        # Dragon's Eye Ability to Find Chests. Set to False to Disable. Default True :Requires Relogin to world
        B:"Find Chests Ability"=true

        # Polarized Stone's Push and pull speed. Default 0.1, 0.1 MIN, 1.0 MAX
        # Min: 0.1
        # Max: 1.0
        D:"Polarized Stone Push and Pull Speed"=0.1

        # Sea Stone's Ability to float in water. Set to False to Disable. Default True
        B:"Sea Stone's Swimming Tweaks"=true

        # Step Height Adjustment when wearing Race Rings. Set to False to Disable. Default True
        B:"Step Height"=true
    }`
Am I doing something wrong? I do see 2 config files so I went ahead and set it to false for both

**Comment by XzeroAir** [comment]
I Apologize, I've been busy and apparently The Email notifications didn't send the message for this post, If you are Using ArtemisLib, then It was a Bug that I Have Just Fixed Which I'm uploading right now, Otherwise Try Deleting the Config File and loading up the game to generate a New one and see if it still doesn't work

**Comment by XzeroAir** [comment]
Assuming The Issue has been resolved, so closing for now, If you still have the issue, let me know
