### ISSUE TITLE
[1.12.2] Conflict with Construct's Armory. Breaks Armory's autostep.

### ISSUE THREAD

**Issue by voidpls** [XzeroAir/Trinkets-1.12.2#14]
Construct's Armory has an armor modifier "High Stride" that gives the user auto-step. Auto-step does not work when testing with only Construct's Armory, Trinkets & Baubles, and their dependencies:
![image](https://user-images.githubusercontent.com/28279553/59813736-ab8d3b00-92e0-11e9-9e5b-8e604cd4bf7a.png)

However, auto-step starts working again as soon as Trinkets is disabled:
![image](https://user-images.githubusercontent.com/28279553/59813801-e42d1480-92e0-11e9-9714-437508f5ada9.png)

**Comment by XzeroAir** [comment]
I'll Try to Look into it sometime tonight/Tomorrow, Thanks for letting me know

**Comment by XzeroAir** [comment]
Alright I think I have a Fix in place, Working fine so far in my testing, I'll Try to get the update out sometime tomorrow or the Day After, Going to do some More Testing First

**Comment by XzeroAir** [comment]
Well, I Found an issue when Testing the Step Height yesterday, Been working on it most of today, but having to rewrite some code, I'm Going to Try and Get the Update out tonight still, but it'll be late if I do.

**Comment by XzeroAir** [comment]
I think I Got it, Things seem to be working, and the Issue I found is fixed, Going to push an Update out, Let me know if any more issues pop up, Going to Close this Issue Now, Update should show up soon-ish
