### ISSUE TITLE
Fairy ring effects not being completely undone upon unequipping. 

### ISSUE THREAD

**Issue by squirrelkiller** [XzeroAir/Trinkets-1.12.2#15]
After removing the Fairy Ring the resize effect wasn't fully undone correctly. At first it didn't return to normal size at all, then after reequipping and removing I was full size, but couldn't climb stairs. After one instance I was full size but could fly still.

**Comment by XzeroAir** [comment]
Are you Using the Latest Version of Trinkets and Baubles? were you on Single Player or Multiplayer/Server.
Also, are You using the Optional ArtemisLib Dependency or no?

**Comment by XzeroAir** [comment]
Closing because lack of Information, and Unable to reproduce
