### ISSUE TITLE
Polarized stone wont stay active when right clicking

### ISSUE THREAD

**Issue by tigersmith12** [XzeroAir/Trinkets-1.12.2#17]
i am playing rlcraft 2.6.3 
minecraft 1.12.2

**Comment by XzeroAir** [comment]
I wasn't able to reproduce the issue, But I've been working on an update, hopefully when it's released, it'll fix the problem

**Comment by tigersmith12** [comment]
it seems the issue is visual and you cant tell if its active till it just works
thank you for your response

**Comment by tigersmith12** [comment]
there is a problem with the bauble system all together on server i guess
when you die/relog the bauble slots need to be re-equiped sometimes not all the time maybe this has an affect
maybe in 1.14 this wont be a problem but time will tell

**Comment by XzeroAir** [comment]
I released a Beta version that should fix the issue, Maybe try that version? 0.26b, If you do, Backup your Saves First though

**Comment by XzeroAir** [comment]
Should be fixed in latest Versions
