### ISSUE TITLE
[Request] Polarized Stone

### ISSUE THREAD

**Issue by luxlacis** [XzeroAir/Trinkets-1.12.2#18]
Hey, I've been using this mod for a bit and was thinking of ways to improve it and one way was to maybe add some sort of particle effect around the items which are being pulled towards the player with the Polarized Stone item. Similar to the particles in Tiered Magnets (https://www.curseforge.com/minecraft/mc-mods/tiered-magnets).

Also, if would be great if you could toggle the magnet with a hotkey so the player wouldn't have to take it out of the baubles inventory all the time.

**Comment by XzeroAir** [comment]
I can add a Hotkey, no problem, I'll have to think about adding particles though

**Comment by XzeroAir** [comment]
Added the Keybind in 0.26b, no Particle Effect for now, If you Try 0.26b, make sure to backup your save first
