### ISSUE TITLE
Polarized stone not staying active.

### ISSUE THREAD

**Issue by Celebrimbatch** [XzeroAir/Trinkets-1.12.2#19]
Playing RLCraft V2.7.1 the Polarized Stone is not staying active when trying to turn it on, this works in singleplayer but not multiplayer.

**Comment by XzeroAir** [comment]
You could Try updating to the Beta Version of 0.26 and see if that fixes the problem, Although if you do, Backup your save file First

**Comment by XzeroAir** [comment]
Finally Found the issue, Mostly Fixed in 0.28
