### ISSUE TITLE
Crashing while going up stairs with the fairy ring.

### ISSUE THREAD

**Issue by Daisukemara** [XzeroAir/Trinkets-1.12.2#20]
[crash-2019-10-08_00.27.53-client.txt](https://github.com/XzeroAir/Trinkets-1.12.2/files/3701079/crash-2019-10-08_00.27.53-client.txt)
![2019-10-08_02 49 49](https://user-images.githubusercontent.com/32429521/66373348-72073b00-e976-11e9-9004-336ce283eccf.png)
![2019-10-08_02 50 13](https://user-images.githubusercontent.com/32429521/66373349-72073b00-e976-11e9-8ada-ea150326e43b.png)
![2019-10-08_02 50 32](https://user-images.githubusercontent.com/32429521/66373350-72073b00-e976-11e9-92e8-a14c10b87c70.png)

This crashes other players in the area, but not myself.  My friend also continued to crash immediately on logging in until I took off the ring and reapplied it.  We were able to reproduce it by just having me walk up the stairs.

**Comment by XzeroAir** [comment]
Redid the code for it, It should no longer cause a crash, Hoping to get an Update out sometime tonight

**Comment by XzeroAir** [comment]
Closing the issue, but if it happens again, or you find something else, Let me know
