### ISSUE TITLE
[Suggestions] More customizablility for pack devs

### ISSUE THREAD

**Issue by Wxrlds** [XzeroAir/Trinkets-1.12.2#21]
It would be nice if you could implement it so every item of the mod can be enabled or disabled via a config option to allow for better customizablility for pack devs i.e.:
```
enablePoisonStone=true
enableEnhancedPotion=true
```

Also for more customizability, it would be nice if we were able to disable certain aspects of some baubles, i.e. the Stone of Inertia Null can toggle if you want to enable knockback resistance. It would be nice if we can also toggle if we want to enable the falldamage resistance which comes with it.

To come to an end, it would be nice if we can toggle which bauble can go in which baubles slot, letting you choose between any, ring, head, and how they are all called.

**Comment by XzeroAir** [comment]
In the Latest Version Nearly everything about the baubles already can be toggled, and Probably by the Time you Read this Message I'll have released another Update with even more config options.
For now, still no toggling of each individual Item though, Might add that in a future update. and about the Stone of Inertia Null, I Agree I Should add a config option for that, but that would mean it would do virtually nothing if you turn it off

**Comment by XzeroAir** [comment]
Added Config Options to Choose the Bauble Slot Each Item uses in 0.28

**Comment by XzeroAir** [comment]
Config Options to Disable Each Individual Trinket/Bauble Added as of 0.29.

**Comment by Wxrlds** [comment]
Thank you so much 🎉
