### ISSUE TITLE
Missing gradle and libs from source

### ISSUE THREAD

**Issue by WiseHorror** [XzeroAir/Trinkets-1.12.2#23]
I wanted to modify the mod a bit for my personal use, and add some ores to the dragon's eye xray but can't build the mod without the dependencies.

**Comment by XzeroAir** [comment]
In the Latest Version of Trinkets and Baubles you can add Any block to the Dragon's Eye Detection ability through the Config or Mod Options in Game, Don't really need to rebuild the mod for that anymore

**Comment by WiseHorror** [comment]
Alright, good to know! Thanks for the reply!
