### ISSUE TITLE
Fairy Ring crash

### ISSUE THREAD

**Issue by craving-death** [XzeroAir/Trinkets-1.12.2#24]
RLCraft V2.8

https://gist.github.com/craving-death/abffcc4cc5b7722f627a96fb4d45f705

**Comment by XzeroAir** [comment]
I'm Not Entirely Sure What exactly is causing that crash, but I am aware it has something to do with Sponge Forge and some combination of Plugins or Mods, but that's as far as I've gotten, That Specific Line that It crashes on is my code trying to access the Vanilla MC Creative Flight Capability for the Ring of the Fairies Bauble, but the Method I'm Referencing is Missing or Modified and it causes a crash, A Quick Fix you can do is go into the Config for Trinkets and Baubles and Turn off the Creative Flight for the Fairy Ring.

If you could provide a List of Plugins you're using, and any extra mods you might have added to the pack, That might help me track down what's causing the issue and see if I Can fix it

**Comment by XzeroAir** [comment]
Alright, I Figured out the Issue, Until I can push an Update, Turn the Config option 
"B:"Change Flight Speed"" To False in the Trinkets And Baubles Config. and you can leave Creative Flight on. I should have an Update out sometime tonight or tomorrow that will hopefully fix it.

**Comment by XzeroAir** [comment]
Alright, Fixed, Closing this, If for some reason it happens again, let me know
