### ISSUE TITLE
Fairy Ring suggestion

### ISSUE THREAD

**Issue by Andr0oS** [XzeroAir/Trinkets-1.12.2#25]
If at all possible, being able to toggle the effects of the fairy ring with a hotkey would be great.

**Comment by XzeroAir** [comment]
I Appreciate you posting a suggestion, I've had a couple people suggest similar things for the Fairy Ring.
and considering I used to play modpacks with Morph in it so it was pretty easy to change size by turning into different creatures. I Completely Understand why it would be nice.
Unfortunately, The "Time" it takes you to unequip or equip the ring, was intended as a "Cooldown" of sorts, I Might add an option to toggle the effect in the future, but it's very low on my priorities for the mod, and It would involve reworking how the Rings work quite a bit.
