### ISSUE TITLE
Ring of the Fairies in RLcraft doest give back lost hearts...

### ISSUE THREAD

**Issue by tealtoxic** [XzeroAir/Trinkets-1.12.2#26]
hi. im havin a problem where i could not recover my lost hearts from becoming a fairy through Ring of the Fairies. Since im playing RLcraft modpack, scaling health's heart container cant even help me recover the lost hearts. any tips? at this point i might not use the Ring of the Fairies cuz i cant regain my magically lost hearts.. heres a copy of the issue i reported at RLcraft modpack page :

What version of RLCraft are you on:  

 2.8.1

 If it's a crash, a crashlog from the crash-reports folder:  

 no crash

 Clear instructions or even images on reproducing:  

wear ring of the fairies takes out hearts  (because you became smaller) but unequipping it doest give back lost heart. And i cant recover lost hearts with heart container.. its like the system know i already reached max obtainable hearts with heart container... i thought it was a glitch so i relog. but same result. any tips?

pls advise.

**Comment by tealtoxic** [comment]
after furthur testing , i managed to fix it by unequipping all accessories and only equip and unequip the ring of fairies, my hearts are back now.

**Comment by XzeroAir** [comment]
Yeah I Recently Learned that if you "Replace" the Ring, rather then unequip it manually, It doesn't properly trigger the unequipping code, So it is a bug, Thank you for Reporting it, I Really do Appreciate it.

**Comment by tealtoxic** [comment]
thank you for your time 💃
