### ISSUE TITLE
Wither Ring crash

### ISSUE THREAD

**Issue by HHServers** [XzeroAir/Trinkets-1.12.2#27]
More info available if needed
[LOG SNIPPET](https://gist.github.com/HHServers/3e76351dd55a5b50dc553eb634916a3e)

RLCraft V2.8.1
Trinkets and Baubles-1.12.2-0.28.1

**Comment by XzeroAir** [comment]
Do you have any more information? Like what was going on prior to the crash?

**Comment by XzeroAir** [comment]
Nvm, I Was able to reproduce the issue, foir now in the Config, Disable the leech effect from the Wither Ring, and that should prevent the issue from happening again, Until I can get a fix for it

**Comment by XzeroAir** [comment]
Fixed as of 0.29
