### ISSUE TITLE
[1.12.2] If some settings in Enhanced Visuals are disabled, certian trinkets will crash the game upon equipping them.

### ISSUE THREAD

**Issue by Z-Tunic** [XzeroAir/Trinkets-1.12.2#29]
Report:
https://pastebin.com/mNJ26EpM

Config:
[config.zip](https://github.com/XzeroAir/Trinkets-1.12.2/files/4050195/config.zip)

Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods: 4
Baubles-1.12-1.5.2
EnhancedVisuals_v1.2.7_mc1.12.2
jei_1.12.2-4.15.0.291
Trinkets+and+Baubles-1.12.2-0.29

-----

I've only tested this with the 'Stone of the Sea' & 'Shield of Honor' Trinkets. In the Enhanced Visuals I have some settings disabled and I assume the Trinket is trying to disable the visual... but it's already disabled... so it crashes. The world will then get stuck in a crash loop unless I change the settings in Enhanced Visuals or remove the mod.

I have attached a zip with the config files that I'm using for Enhanced Visuals & Trinkets & Baubles to hopefully aid with fixing the crash. Just equip those two trinkets that I mentioned with the config files inside the zip and the game will crash as soon as they're equipped.

**Comment by XzeroAir** [comment]
Was able to reproduce it, Yep, I Did a stupid mistake, Going to have to push a 0.29.1.
Thank you Very Much for Letting me know. Just Fixed it, gonna double check things before uploading a hotfix.

**Comment by XzeroAir** [comment]
Alright, Can't get it to crash anymore, think it's good, released a Hotfix, if things are good, Let me know.
