### ISSUE TITLE
crash on server

### ISSUE THREAD

**Issue by jonqrandom** [XzeroAir/Trinkets-1.12.2#3]
forge 1.12.2-14.23.0.2515 trinkets 0.10 baubles 1.51
https://hastebin.com/ibuvacoqif

**Comment by XzeroAir** [comment]
Thank you for posting, I'll look into it as soon as possible

**Comment by jonqrandom** [comment]
no hurry on my end, just letting you know :)

**Comment by XzeroAir** [comment]
I've Managed to fix it, Uploaded new version, should be processed soon

**Comment by jonqrandom** [comment]
hey, sorry i missed your reply, and thank you, it works :)
