### ISSUE TITLE
Ender Tiara Crash

### ISSUE THREAD

**Issue by serioux1337** [XzeroAir/Trinkets-1.12.2#30]
Crash and Savegame Corruption (Crash in Loading Screen)

I equipped the Ender Tiara and it crashed, sometime before i equipped it and it did not crash.
Pack: RLCraft

Crash Report
https://pastebin.com/DxD1rb7U

**Comment by serioux1337** [comment]
ok the crash only occurs in combination with enhancedVisuals Mod if the slender-handler is disabled manually (had to do it for a mob farm), so this issue may be closed

**Comment by XzeroAir** [comment]
Yeah, Unfortunately I Made a really stupid mistake and forgot to check if the effect was disabled, Which I've Fixed in 0.29.1 so unfortunately the only solution is to enable the effect again, or to update Trinkes and Baubles.
