### ISSUE TITLE
Trinket and baubles ran into an issue

### ISSUE THREAD

**Issue by Exy-mat** [XzeroAir/Trinkets-1.12.2#31]
https://paste.dimdev.org/ukamilemew.mccrash

**Comment by XzeroAir** [comment]
Vanilla Fix Likes to kick up Errors or "Crashes" over every minor thing.
I am looking into the reason why Vanilla Fix even sees an issue there, but The Line that it points to shouldn't be causing any issues, Did it crash and bring you back to the main menu?
and when did the error happen, on log in, or when you changed Dimension?

**Comment by Exy-mat** [comment]
It happens every other time, kind of random actually. It doesn't bring me back to the main menu tho

**Comment by XzeroAir** [comment]
Same issue as https://github.com/XzeroAir/Trinkets-1.12.2/issues/28
