### ISSUE TITLE
Server join crash

### ISSUE THREAD

**Issue by Aeron216** [XzeroAir/Trinkets-1.12.2#33]
https://paste.dimdev.org/roderevubi.mccrash

Issue started happening after updating to the latest version of **Enhanced Visuals** (1.3.6) and attempting to join our server, this does not happen when creating a new local world.

And I'm posting this here since the crash reports points towards **Trinkets and Baubles**.

**Comment by XzeroAir** [comment]
Hello, And Thanks For Reporting, I'm not Entirely Surprised, CreativeMD has been doing a rewrite of sorts and is adding better access to alter the visuals, In the process it probably broke the hacky way I've been doing it so far.
**Assuming you're using 0.29.2 of Trinkets and Baubles, if you go into the Config for Trinkets and Baubles and disable the Enhanced Visuals Compatiblity, That should Prevent the crash.**
If it still happens let me know, but I am already planning to switch over to CreativeMD's new System, Which Hopefully should prevent crashes like that from happening in the Future.

**Comment by Aeron216** [comment]
Still crashed unfortunately after disabling the support from the config. For now I just downgraded Enhanced Visuals version to 1.2.7 and it's back to working.

**Comment by XzeroAir** [comment]
Hmm, Strange it still crashed, but alright, thanks for letting me know, 
I'm Hoping to get 0.30 out sometime before the end of the month.

**Comment by Aeron216** [comment]
Yeah and it didnt even generate a log this time, only a generic "Fatal Error" message after getting booted back to the main menu.

Anyway, thanks for your hard work. Great mod, thats why I'd rather just downgrade Enhanced Visuals instead.

**Comment by XzeroAir** [comment]
I'm not sure if I'll Manage to get the update out before the end of the month, but, I Did check out Enhanced Visuals Update, CreativeMD added some API Events and I've already finished coding the Compatibility Features, Once I Do Manage to get 0.30 out, As long as Enhanced Visuals doesn't change the Api code, it shouldn't cause a crash anymore.

Also, Lol, Thank you for Using my Mod, Glad you Enjoy it that much, There's Going to be a couple of new Trinkets in 0.30, so I hope you look forward to that.

**Comment by XzeroAir** [comment]
Translation work took a lot longer then I had hoped so only 1 new trinket in 0.30, But I've officially updated 0.30 and I use the new Enhanced Visuals Api, so Hopefully there shouldn't be issues anymore, but let me know if something pops up
