### ISSUE TITLE
Ring of Fairies perspective didn't change into smaller size

### ISSUE THREAD

**Issue by Geezt435** [XzeroAir/Trinkets-1.12.2#35]
![2020-03-31_13 32 32](https://user-images.githubusercontent.com/46617557/77990740-b3403c80-7354-11ea-80bf-845ffacda154.png)
![2020-03-31_13 32 26](https://user-images.githubusercontent.com/46617557/77990752-b9ceb400-7354-11ea-8323-74dd86bbbe92.png)

Ring of Fairies supposed to make my camera view smaller, didn't work.
The FOV is supposed to become smaller, but it didn't work, it normally does.

**Comment by Geezt435** [comment]
New info:
So I tested with player hitboxes and it shows this 
![2020-03-31_13 43 58](https://user-images.githubusercontent.com/46617557/77991190-c43d7d80-7355-11ea-901d-b405e99078c3.png)
The red thing is not on me but above me, 
I still don't know how to fix it

**Comment by XzeroAir** [comment]
Have you Changed any Configs?
Are you in a Custom Modpack?
You said it normally works, did you add or change anything prior to the issue happening?
Does Taking it off and putting it back on fix it?
the only thing I can guess at the moment is maybe a Mod Conflict of some sort.

**Comment by Geezt435** [comment]
1. I didn't change any configs
2. I'm not on a mod pack, but I do put on a lot of mods
3. I did add mods, still looking for it but didn't manage to find any
4. Nope
5. Probably it's the better combat mod or ido mod

**Comment by XzeroAir** [comment]
Yes, the Red Line is the Players "Eye Height" it's what determines your Camera/Line of Sight, Oddly It also Determines if you Take Damage in blocks as well lol
No clue why they coded it to do that.
Anyway, Yeah, Sounds like a Conflict of some sort, I know More Player Models Causes an issue, so do some of the Mods like Morph and Metamorph

**Comment by Geezt435** [comment]
I found the answer, it's this mod who cause it:
- Indicatia mod
- SteveKun'Gslib

Also, by the way, I can't climb with the Ring of Fairies and I always get damage when I touch block with Ring of Fairies, the Eye Height too wide, can you make it smaller and reenable the ring climb ability?

**Comment by XzeroAir** [comment]
Looking at those Mods Source Code, Yeah, It's Indecatia that's Causing it, They're just Constantly Setting the Players EyeHeight back to the Default every Tick, Not Really anything I Can do about it,

The Taking Damage when touching a block is also probably caused by that.

**Comment by Geezt435** [comment]
Okay, so I contacted SteveKun ( Indicatia mod owner ) and I hope it fixed soon.

Talking about fixing, Ring of Fairies model actually suffocate you when you touch block instead of climbing or just bumping
