### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by EnderBro123** [XzeroAir/Trinkets-1.12.2#39]
Mod crashes with or without the needed Dependencies installed.

Crash report says something related to the mod, but something else may also be 
causing this. I can't read crash reports though. All mod/forge info stuff is in the report. 
Only way to fix this was by downgrading to 1.12.2-0.30-Pre-release-1.5. Otherwise, 
anything above this causes the crash.

[crash-2020-07-07_11.18.57-client.txt](https://github.com/XzeroAir/Trinkets-1.12.2/files/4886512/crash-2020-07-07_11.18.57-client.txt)

**Comment by XzeroAir** [comment]
If you're using Enhanced Visuals, Trinkets and Baubles 0.30+ Requires Enhanced Visuals 1.3.6 or Later
