### ISSUE TITLE
VanillaFix crash

### ISSUE THREAD

**Issue by Alfiekins** [XzeroAir/Trinkets-1.12.2#40]
So VanillaFix is acting up and I can't seem to figure out what's going on. Perhaps you could look into this? Cheers. 

[crash-2020-07-15_17.09.24-client.txt](https://github.com/XzeroAir/Trinkets-1.12.2/files/4924280/crash-2020-07-15_17.09.24-client.txt)

**Comment by XzeroAir** [comment]
It's an issue related to the First Aid Compatability for the Shield of Honor, From the looks of it, You're using a Really really outdated Version of First aid, Which Doesn't have the Method I'm using, You can try disabling the First aid Compat in the Trinkets and Baubles Config to see if that fixes it, but You're probably going to need to update First aid to a newer version

**Comment by XzeroAir** [comment]
Assuming you've resolved the issue, if not, let me know, Closing this issue for now
