### ISSUE TITLE
When I add this mod to my modpack, it failed.

### ISSUE THREAD

**Issue by C-Zking** [XzeroAir/Trinkets-1.12.2#41]
I use the newest mod , and it still failed.
This is the crash-resport
[crash-2020-08-31_19.31.56-client.txt](https://github.com/XzeroAir/Trinkets-1.12.2/files/5150078/crash-2020-08-31_19.31.56-client.txt)

**Comment by C-Zking** [comment]
In addition, I made modpacks myself and added a lot of MODS

**Comment by XzeroAir** [comment]
From the looks of it, You've hit the max amount of Potions the game can have, You'll need a Potion ID Limit increasing mod

**Comment by C-Zking** [comment]
Thank you very much. I did what you said and succeeded.
