### ISSUE TITLE
(Race rings) When playing multiplayer, player model size doesn't change with rings for other people. It DOES work with potions, though. How to fix?

### ISSUE THREAD

**Issue by roccscout** [XzeroAir/Trinkets-1.12.2#42]
If my friend equips the fairy ring, I don't see his hitbox transform. However, if he drinks the fairy potion, he DOES transform.
And reason behind this?

**Comment by XzeroAir** [comment]
Without any more information, I can only guess you've got a mod that is causing an issue.
I need to know what version of Trinkets and Baubles you're using.
also, are you using a Modpack of some sort, or a custom one?

**Comment by roccscout** [comment]
Thanks for the quick response! Sorry for being so lazy, let me get you some info: 

Version 1.12.2,  TnB  0.30-.jar
Custom modpack:
![delete2](https://user-images.githubusercontent.com/71896090/94472027-60bace00-0187-11eb-9c45-c7958ae95d05.JPG)
![delete1](https://user-images.githubusercontent.com/71896090/94472030-61536480-0187-11eb-8ef8-bf6c51a48dd3.JPG)

I am NOT using Artemis Lib, should I be?

**Comment by XzeroAir** [comment]
No, Should be fine if you're not using ArtemisLib, uh, can you Test without Ido?
Ido I believe brings swimming to 1.12 right? those kinds of mods tend to have issues with the Races because it edits the Players Bounding Box

**Comment by roccscout** [comment]
Tried it without IDO, and without many other mods as well. Still happens. I don't believe many mods I'm using adjust player hitbox...

**Comment by XzeroAir** [comment]
Hmm, it happens when you're standing near each other? does it fix if you relog after they equip it?
The only other thing I can think of is if you're using Spongeforge for your server

**Comment by roccscout** [comment]
No spongeforge, relog doesn't help either. Very odd.

**Comment by roccscout** [comment]
Definitely appreciate your interest and help!

**Comment by XzeroAir** [comment]
Hmm, Only thing left I can think of is if you're trying to equip 2 different rings at the same time, Wearing more then 1 will cancel each other out and you'll turn back to normal and get no benefit from either ring.

Another thing to note is, Potions have Priority, then Rings, then The permanent transformation Items, so you could be permanently a Fairy, and wear a Ring of Dwarves, which will turn you into a Dwarf, then, if you used a Titan Transformation Potion, You'd then turn into a Titan,

I didn't really do anything drastically different with how the information for transformations are synced in 0.30 compared to 0.29, so there shouldn't be any reason for it not to work at all.

only thing I can really think to suggest is try Updating from 0.30 to 0.30.1

**Comment by XzeroAir** [comment]
So this was most likely an issue with Ido, because of how they do their Swimming tweaks, currently no solution, hope to figure something out in the future, for now, Closing the issue
