### ISSUE TITLE
Bauble suggestion

### ISSUE THREAD

**Issue by blockbreaker1361** [XzeroAir/Trinkets-1.12.2#5]
How about a bauble that negates wither and poison effect. You could make 2 recipes for it with a config option for easy recipe or hard(requires nether star and diamonds?), IDK you make that decision. Just thought I'd throw this out there.

**Comment by XzeroAir** [comment]
Sorry about the Late Reply, but That's not a bad idea, I'll look into it and see what I can do, currently working on another project atm so this is on the backburner for now, but I'll Write it down in my notes and keep it in mind when working on it next, Thank you for your Suggestion

**Comment by XzeroAir** [comment]
Good news everyone! Lol
I'm currently working on adding in a few more items that can negate wither and poison, but I'm still thinking about how to balance it, but I should have an update out within the next few days from posting this message, so if your still interested, keep a lookout

**Comment by XzeroAir** [comment]
Alright, Suggested Items have been added, I Might do some re-balancing or change the items a bit in the future though, let me know if you have any more suggestions, and thanks for using my mod
