### ISSUE TITLE
Shield of Honor Resistance does not stack with Potion Ring of Resistance

### ISSUE THREAD

**Issue by szikra** [XzeroAir/Trinkets-1.12.2#57]
The wiki says about Shield of Honor that "you receive the Resistance effect, which stacks with other sources of Resistance."
I have a Potion Ring of Resistance (from Potion Fingers mod) equipped already and Resistance effect do not stack with it.

(Ring gives Resistance 1, Shield alone gives Resistance 1, Shield+Ring also Resistance 1, two rings give Resistance 2 regardless of Shield, so the rings do stack but the Shield does not seem to.)

I'm playing RLCraft which includes version 0.29.2 of this mod, not sure if this was patched since then, or if this is intended behavior and the wiki is wrong/incomplete.

**Comment by XzeroAir** [comment]
due to changes done with Potion Rings, 0.29.2 of T&B stopped stacking properly with them.
I updated the code and they should work again as of 0.31 of T&B, RLCraft will include this version in the 2.9 Update.
But yes, Already fixed.
