### ISSUE TITLE
Update 0.31 Broke Keybind Modifiers

### ISSUE THREAD

**Issue by TwiliDiamondOcelot** [XzeroAir/Trinkets-1.12.2#58]
**Describe the bug**
After updating the mod from 0.30 to 0.31 I noticed that the forge keybind modifiers no longer worked. I had used 'shift + [key]' for this mod's keybinds, but in 0.31 these no longer worked. I tested all keybind variations and none of the modifiers worked, only single keys.

**Version (please complete the following information):**
 - Version 0.31

**Comment by XzeroAir** [comment]
Yeah, I have a good idea as to why that's happening, I'll look into it and see what I can do about it, unfortunately, there's no current solution.
I'll have to build a new version to fix it.

**Comment by XzeroAir** [comment]
Thanks for the report, and sorry it took so long, but Sometime tomorrow I should have an update out that fixes this.
