### ISSUE TITLE
Bauble suggestion: pumpkin tiara

### ISSUE THREAD

**Issue by migmolrod** [XzeroAir/Trinkets-1.12.2#6]
The idea would be to have a bauble that has the same passive effect that the pumpkin: allow player to look at endermens' eyes without provoking them. And also limiting vision (like the regular pumpkin does).
Since it's a quite powerful effect (because it leaves open your vanilla head slot for your diamond overpowered helmet, that's the whole point of the trinket), I guess the recipe should be relatively expensive.
Maybe with Eye(s) of Ender (not Ender Pearl), the glowing ingots and, of course, a pumpkin. Or even a previous stone as prerequisite (like the polarized one, since this also deals with avoiding enemies)

**Comment by XzeroAir** [comment]
Hmm, Interesting Idea, I'll play around with it, If it works out, I might add it

**Comment by XzeroAir** [comment]
I've been working on this but it requires a lot more work then I thought it would, I'll add this to my Todo list.
But unfortunately it will not be in the next update, but like I said, I'll continue to work on it.

**Comment by XzeroAir** [comment]
Oh, Good news, got it working ahead of time, should be added in the next update
