### ISSUE TITLE
causing errors in other mods

### ISSUE THREAD

**Issue by Edel-Lilies** [XzeroAir/Trinkets-1.12.2#62]
Install mod Sweet magic and Trinkets and Baubles,than sweet magic can't spawn any mod mob.
Use spawner and eggs will be game crash,delete Trinkets and Baubles,Sweet Magic back to normal.
[logs.zip](https://github.com/XzeroAir/Trinkets/files/8523698/logs.zip)

**Comment by XzeroAir** [comment]
Hello, Thank you for reporting this Error, after looking into it, I think it might actually be on Sweet Magic's Side.
If you don't mind testing, could you attempt to spawn a SkullFrost with an Egg and let me know if it crashes.

**Comment by Edel-Lilies** [comment]
Ok,I also reported to Sweet magic,thanks you help me.

**Comment by XzeroAir** [comment]
To Clarify, Looking at their mods source, Assuming it's accurate, they seem to be missing some overrides in some of their entities.
The "EntityIfritVerre" entity is lacking overrides, but the "EntitySkullFrost" entity has overrides and seems to be fine.
If you were able to spawn an EntitySkullFrost with T&B installed, then It's most likely on Sweet Magics end.
Looking at the actual code and checking what's crashing, It's Failing on a Check that's used to make sure the entity is not a Boss Mob, tracking it down, Sweet Magic is overriding that check for their entities and checking the entities max health, but it's failing to get the entities health, resulting in a Null pointer crash

**Comment by mcmso** [comment]
> Ok,I also reported to Sweet magic,thanks you help me.

Ok,I also reported to Sweet magic,thanks you help me.
