### ISSUE TITLE
Book GUI rendering error due to mana bar settings in config

### ISSUE THREAD

**Issue by VVolfrann** [XzeroAir/Trinkets-1.12.2#67]
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2860
Trinkets and Baubles Version: 0.31.4

Issue:
Book GUIs from various mods will render with a permanent white border around their edges. Mods used to test were Village Names 4 and Extra Utilities 2. This occurs due to the Mana Bar from Trinkets and Baubles, specifically the following config setting:
```
# Should the Mana Bar show even when full
            B:"02. Show when Full"=true
```
When set to false, the issue occurs 0% of the time. When set to true as above the issue occurs 100% of the time. The mana bar works as the setting intends it to, and other GUI seem unaffected, but I have not tested too many of them to know for certain. Images have been attached to demonstrate the issue exactly

![VN4](https://user-images.githubusercontent.com/66946653/176569458-c8c7fee7-28f6-494d-a185-607c9b42c4e8.png)
![EU2](https://user-images.githubusercontent.com/66946653/176569462-4ed7d076-0979-4a08-9b66-6988507d2426.png)

**Comment by XzeroAir** [comment]
Hello, Thank you for the bug report, I'll have to test, but this might already be fixed in my dev environment, Uhm, Not sure exactly when I can get an update out, but I am working on another 1.12 update due to some reasons, I'll add this to my Todo list
