### ISSUE TITLE
Incompatibility with More Player Models

### ISSUE THREAD

**Issue by 0nis** [XzeroAir/Trinkets-1.12.2#68]
**Describe the bug**
The resizing attribute of the race rings does not work with the mod More Player Models. Upon equipping a ring, the screen will immediately start to glitch.

**Screenshots**
Since a screenshot doesn't show the problem, here's a video of the issue: https://streamable.com/edmt78

**Version**
 - Minecraft version 1.12.2
 - Forge version 14.23.5.2859
 - Trinkets and Baubles version 0.31.4
 - More Player Models version 05Dec19

**Comment by NyanMC** [comment]
i'm not xzeroair, but this is known and unfixable (at least on trinkets' side)

not sure why it isn't listed on the curseforge page as an incompatibility, it really should be

**Comment by XzeroAir** [comment]
Yeah, sorry about the late reply, as Nyan mentioned, It's not fixable on my end, More Player models sets the players EyeHeight every tick, your best bet is to turn off T&B's EyeHeight Adjustments, and attempting to use More Player Models, and that sort of gives you some ability to manage it.
