### ISSUE TITLE
Rings of transformation wont work

### ISSUE THREAD

**Issue by Ab0we** [XzeroAir/Trinkets-1.12.2#69]
Hi. I just got Dragon's ring and the wings wont show up and I cant fly too. I tried Fairy ring and same issue. I play on my server. Allow-flight is set on true. Im running the latest version of the RLCraft and Trinkets and Baubles version 0.31.4. Tysm for an answer!

**Comment by XzeroAir** [comment]
Sorry about the late reply to this.
In your inventory, open up the race customization/stats gui, the little blue orb at the bottom of your character preview, in that set the "Show Trait" button on the left side, back to true.
