### ISSUE TITLE
Crash and possible incompatibility with EB

### ISSUE THREAD

**Issue by Sereath** [XzeroAir/Trinkets-1.12.2#73]
**Describe the bug**
Installing both this mod (ElectroblobsWizardry-4.3.9)
and Trinkets and Baubles (Trinkets and Baubles-32.4)
can cause a crash if you try to wear the Ender Crown from Trinkets and Baubles on your head.

**Screenshots**
The exact moment client froze. Same thing happened in a totally different MC instance with fewer mods, log: https://gist.github.com/Sereath/6582699330af3a71cfebd46bcd6787f4
![image](https://user-images.githubusercontent.com/54506307/235822388-5932bfda-4c4c-4889-a293-dd625700391a.png)

**Version (please complete the following information):**
 - Trinkets and Baubles-32.4

**Additional context**
https://gist.github.com/Sereath/6582699330af3a71cfebd46bcd6787f4

And it will crash again if to try to reenter that world:

https://gist.github.com/Sereath/cb5c82a91a610951ef27ea0ee8a1be72

-

This first happened in a big modpack, but that one didnt even give me a crash log:

https://gist.github.com/Sereath/511f7033a5205b3ee3aec563c02e801c

I have also already reported this to Electroblob's Wizardry
https://github.com/Electroblob77/Wizardry/issues/850

**Comment by XzeroAir** [comment]
That's interesting, I actually have Electroblobs in my dev environment, and I've never had that crash before, Do you know if it only happens when trying to equip in creative mode?

**Comment by Sereath** [comment]
Tried in survival mode and it also crashed.

Survival:
https://youtu.be/Z_LgD83pMaI
https://gist.github.com/Sereath/1a6e431e0a1c72d8da6cc39e6f7c5d47

Creative:
https://youtu.be/EBVyDlL5uPo
https://gist.github.com/Sereath/474baec416a4ceb9e195276fb1639f0f

**Comment by XzeroAir** [comment]
Ok, so I'm using Electroblobs 4.3.4 in my Dev Environment, I wonder if something changed.

**Comment by XzeroAir** [comment]
oh, I figured out the issue, I don't know how I missed that.
Looking at the issue, I'm confused how it doesn't crash in other scenarios.
I can probably push a hotfix sometime in the next few days.

**Comment by Sereath** [comment]
Sure, take your time. Thank you.

**Comment by XzeroAir** [comment]
Fixed as of 0.32.5, and available on curseforge
