### ISSUE TITLE
Dwarf Ring

### ISSUE THREAD

**Issue by Papillion1** [XzeroAir/Trinkets-1.12.2#76]
**Describe the bug**

**Screenshots**

**Version (please complete the following information):**

**Additional context**

Hello, I started an Rlcraft server with my friends and we were messing around with the rings. I removed the dwarf ring and now I’m stuck the size of a dwarf, and I can’t seem to revert back to normal size and health, I’ve tried everything, please help.

Rlcraft 2.9.3

**Comment by XzeroAir** [comment]
did you try relogging after taking it off?
And have you tried using the Potion of Restoration?
