### ISSUE TITLE
Commands /xat help Don't work?

### ISSUE THREAD

**Issue by Jennifercutixx** [XzeroAir/Trinkets-1.12.2#77]
Issue: Not sure if this is a bug or never intended it to be in the mod. But I noticed while making my modpack that theirs a command line for using commands but in game they don't work at all. Wonder if this is a bug or not intended to be inside the mod.

Version: [1.12.2], Trinkets and Baubles v32.4

Image listed below:
![image](https://github.com/XzeroAir/Trinkets/assets/60190810/1f951af7-8d08-4c30-a465-cee003b3e835)
Glimplse cut:
![image](https://github.com/XzeroAir/Trinkets/assets/60190810/8e28948f-5d14-4e95-a841-9373963e76c0)

Any info would be useful due to intergrating the mod into my ModPack.

**Comment by XzeroAir** [comment]
Sadly, I really haven't done much with the Commands yet, Sometime soon I'll be releasing an update for 1.12 to incorporate some compatibility and bug fixes, I will try to expand on the commands a bit, assuming I can find the time for it.

**Comment by Jennifercutixx** [comment]
That's okay and I'll be looking forward to the update and if you could expand on commands. Would be amazing, SInce I am trying to intergrate the races with a command system and can allow people to switch classes from command using better questing. And if you could get it working would be fantastic since. I my self is trying to learn 1.12.2 modding for intergrating mods more cleanly into my pack. 
Can understand if it takes a long time since 1.12.2 modding (modding in general) is time comsuming. Especially making it work.

But thank you for your time in develpoing this fantastic mod and don't give up on your amazing mod. Even if sometimes can make you pull your hair out. ^^

**Comment by NyanMC** [comment]
for a case like that it might not be a bad idea to add a command which opens the race selection menu @XzeroAir hint hint nudge nudge

**Comment by XzeroAir** [comment]
Although they're bare bones, and needs more work, Commands are now functional as of 0.32.5
