### ISSUE TITLE
32.4 Flight speed in config do not work

### ISSUE THREAD

**Issue by WeleSS2** [XzeroAir/Trinkets-1.12.2#78]
**Describe the bug**
Config, changing fly speed doesn't work correctly.

Previously on RLCraft changing fly speed worked, now when i'm changing fly speed for fairy and dragon in config it doesn't work.
Tested both bools true and false. None of them work.
This problem is kinda annoying to deal with on our RolePlay modpack so i would appreciate if it could get fixed.

**Screenshots**
They can't help

**Version (please complete the following information):**
 32.4

**Comment by XzeroAir** [comment]
when you change a value for the Flying Speed, Try restarting the game and let me know if it still doesn't work

**Comment by WeleSS2** [comment]
![image](https://github.com/XzeroAir/Trinkets/assets/86500144/1c7ca67f-8468-45f4-b34a-765b97508fde)

With this setting i should be able to fly 20x faster than on creative, but i'm flying normally. 

I checked a github code and it seems that everything is ok, so maybe it's interaction with other mod or something like that? If you want i can perform some tests which can help. If you're willing to look for a fix

The problem only is with fairy, dragon looks like is working fine

Update, you can close. If mana cost is 0 then changing fly speed do not work, when i set it to 0.001 it's working.

**Comment by XzeroAir** [comment]
Hmm, Yeah, It looks like I need to rewrite the logic for handling the flight.

**Comment by XzeroAir** [comment]
fixed in 0.32.5
