### ISSUE TITLE
[1.12.2] Ring of Fairies/Dwarfs doesn't work in the bottom Baubles Ring Slot.

### ISSUE THREAD

**Issue by Z-Tunic** [XzeroAir/Trinkets-1.12.2#9]
Minecraft: 1.12.2
Forge: 14.23.5.2778

Mods: 2
Baubles-1.12-1.5.2
Trinkets+and+Baubles-1.12.2-0.19

-----

![](https://cdn.discordapp.com/attachments/377171551155650560/517746038426173461/ringresizeslotissue.PNG)

If these rings are in the top slot... they work, but if in the bottom slot... nothing happens. Unless... this is intended so the player can't stack the effects? The other rings seem to work fine in the bottom slot like the Wither Ring.

P.S.
If you swap out a resize ring with another ring in the same slot, your model won't resize but your hitbox will act as normal, if you unequip the ring so the slot is empty... your model will resize back to normal.

**Comment by XzeroAir** [comment]
Also, Sorry it took so long in replying, I've been busy helping another modder out with one of their projects and hadn't had the chance to check everything

**Comment by Z-Tunic** [comment]
It's alright, no rush.

**Comment by XzeroAir** [comment]
Ok, update pushed, I think it was fixed, If still have issues, let me know

**Comment by Z-Tunic** [comment]
Appears to work fine now, also fixed the bug where if you switch the ring out with another ring, the model wouldn't re-scale unless the slot was empty. All good.

**Comment by WhoCaresWhoIAm** [comment]
i have a problem and dont know how to fix it sadly so me and my friend both used fairy dew and cant revert back to normal now any way to fix that? like with a command or so?

**Comment by XzeroAir** [comment]
> 
> 
> i have a problem and dont know how to fix it sadly so me and my friend both used fairy dew and cant revert back to normal now any way to fix that? like with a command or so?

This isn't even close to the issue you're having, why are you posting that here?
You Remove the effect by using the Potion of Restoration, Do not use the Splash potion or Lingering Versions.
I Also have a Wiki Now thanks to @NyanMC 
https://github.com/XzeroAir/Trinkets-1.12.2/wiki/z.-Miscellanious
